openapi: 3.0.3
info:
  title: Naecipe Cookbooks API
  description: 레시피북 CRUD API
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /cookbooks:
    get:
      summary: 내 레시피북 목록 조회
      description: |
        현재 사용자의 모든 레시피북을 조회합니다.
        레시피북이 없는 경우 "내 레시피북"이 자동 생성됩니다.
      operationId: getCookbooks
      tags:
        - Cookbooks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 레시피북 목록
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CookbookListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: 레시피북 생성
      description: 새 레시피북을 생성합니다.
      operationId: createCookbook
      tags:
        - Cookbooks
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CookbookCreateRequest'
      responses:
        '201':
          description: 레시피북 생성됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CookbookResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /cookbooks/{cookbookId}:
    get:
      summary: 레시피북 상세 조회
      description: 특정 레시피북의 상세 정보를 조회합니다.
      operationId: getCookbook
      tags:
        - Cookbooks
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/CookbookId'
      responses:
        '200':
          description: 레시피북 상세 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CookbookDetailResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: 레시피북 수정
      description: 레시피북 정보를 수정합니다.
      operationId: updateCookbook
      tags:
        - Cookbooks
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/CookbookId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CookbookUpdateRequest'
      responses:
        '200':
          description: 레시피북 수정됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CookbookResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: 레시피북 삭제
      description: |
        레시피북을 삭제합니다.
        기본 레시피북(is_default=true)은 삭제할 수 없습니다.
        삭제 시 저장된 레시피 연결 정보도 함께 삭제됩니다.
      operationId: deleteCookbook
      tags:
        - Cookbooks
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/CookbookId'
      responses:
        '204':
          description: 레시피북 삭제됨
        '400':
          description: 기본 레시피북은 삭제 불가
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /cookbooks/reorder:
    patch:
      summary: 레시피북 순서 변경
      description: 레시피북의 표시 순서를 변경합니다.
      operationId: reorderCookbooks
      tags:
        - Cookbooks
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CookbookReorderRequest'
      responses:
        '200':
          description: 순서 변경됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CookbookListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    CookbookId:
      name: cookbookId
      in: path
      required: true
      description: 레시피북 ID
      schema:
        type: string
        format: uuid

  schemas:
    CookbookCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 레시피북 이름
          example: "한식 모음"
        description:
          type: string
          maxLength: 500
          description: 레시피북 설명
          example: "한식 레시피 모음집"
        cover_image_url:
          type: string
          format: uri
          maxLength: 500
          description: 커버 이미지 URL
          example: "https://example.com/images/cover.jpg"

    CookbookUpdateRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 레시피북 이름
        description:
          type: string
          maxLength: 500
          nullable: true
          description: 레시피북 설명 (null로 삭제 가능)
        cover_image_url:
          type: string
          format: uri
          maxLength: 500
          nullable: true
          description: 커버 이미지 URL (null로 삭제 가능)

    CookbookReorderRequest:
      type: object
      required:
        - cookbook_ids
      properties:
        cookbook_ids:
          type: array
          items:
            type: string
            format: uuid
          description: 원하는 순서대로 정렬된 레시피북 ID 목록
          example:
            - "550e8400-e29b-41d4-a716-446655440001"
            - "550e8400-e29b-41d4-a716-446655440002"

    CookbookResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 레시피북 ID
        name:
          type: string
          description: 레시피북 이름
        description:
          type: string
          nullable: true
          description: 레시피북 설명
        cover_image_url:
          type: string
          nullable: true
          description: 커버 이미지 URL
        sort_order:
          type: integer
          description: 정렬 순서
        is_default:
          type: boolean
          description: 기본 레시피북 여부
        saved_recipe_count:
          type: integer
          description: 저장된 레시피 수
        created_at:
          type: string
          format: date-time
          description: 생성 시각
        updated_at:
          type: string
          format: date-time
          description: 수정 시각

    CookbookDetailResponse:
      allOf:
        - $ref: '#/components/schemas/CookbookResponse'

    CookbookListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CookbookResponse'
        total:
          type: integer
          description: 전체 레시피북 수

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: 에러 메시지
        code:
          type: string
          description: 에러 코드

  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: 인증 필요
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
